### ISSUE TITLE
Потенциальная утечка памяти

### ISSUE THREAD

**Issue by non-descriptive** [Rofl113/StateMachineForward#1]
https://github.com/Rofl113/StateMachineForward/blob/823bea89ef6d1c63a2a6319f79192fe1f75653cf/frontend/MAIN/main.cpp#L85

```cpp
		auto mana = new ManagerMessages; // Выделение 
		if (!mana)
		{
			return -1;
		}
		manager = std::unique_ptr<ManagerMessagesControl>(mana);
		mana = nullptr; // удаление указателя на выделенный объект
```

**Comment by non-descriptive** [comment]
Ниже еще такая же утечка 
https://github.com/Rofl113/StateMachineForward/blob/823bea89ef6d1c63a2a6319f79192fe1f75653cf/frontend/MAIN/main.cpp#L96

**Comment by Rofl113** [comment]
"Я так вижу" (с)
